- src/api.rs
- tests/api_test.rs
The Document struct is obsolete and this removes it and merges its
functionality with JsonApiResponse
> feature: Merge Document and JsonApiResponse

- src/api.rs
- tests/api_test.rs
http://jsonapi.org/format/#document-top-level
> The members data and errors MUST NOT coexist in the same
> document.
> bugfix: Not to include data and errors in a same document

- src/api.rs
- tests/api_test.rs
Enum size is bounded by the largest variant. The Single(Resource) variant is disproportionately large.
> feature: Box the PrimaryData::Single variant

- src/api.rs
- src/query.rs
- tests/api_test.rs
Hi,
I noticed we're generating 'dense' structs for errors, resources and documents.
For example, we generate:
{"data": {...}, "meta": null, "included": null, "links": null, "jsonapi": null }
Instead of:
{"data":{...}}
This causes issues with the json_api_client ruby gem, and probably a number of other clients, which look for keys to exist before they start processing, but then error out because they found a null value instead of an object.
I looked at the spec and the jsonapi github repo trying to figure out which library was wrong (client or server), and although the json api spec does not explicitly say to set missing keys to null instead of omitting them altogether, there are a number of reasons to think using sparse structures is correct:
- The examples in the jsonapi.org website are …
> Use and serialize sparse structs

- Cargo.toml
Using strict locked versions like '1.0.12' leads to block updating dependencies and may cause compiler errors due to using different `serde` crate versions.
> Update and relax versions in Cargo.toml

- src/api.rs
- tests/api_test.rs
Fixes https://github.com/michiel/jsonapi-rust/issues/30
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/michiel/jsonapi-rust/31)
> Use an empty HashMap if attributes is not supplied

- src/query.rs
- tests/query_test.rs
Parses sort query parameter as described in the spec [here](https://jsonapi.org/format/#fetching-sorting).
Addresses issue #52
> feat: Support sort query parameters

- Cargo.toml
It was previously linking to:
https://travis-ci.org/https://travis-ci.org/michiel/jsonapi-rust/
> Fix cargo/crates.io Travis CI badge

- src/model.rs
This will enable support for models with fields that are recursive.
Closes #51
> :sparkles: Derive JsonApiModel for Box<M> where M: JsonApiModel

- src/array.rs
- src/lib.rs
- src/model.rs
- tests/model_test.rs
Allows an `Option<Vec<M>>` to be used as a "has many" resource.
Closes #56
> :sparkles: Enable support for "maybe has many

- src/query.rs
This is required for our JSON API project.
> Derive Clone for Query

- src/query.rs
- tests/query_test.rs
Break up parameter parsing into helper functions to reduce cyclomatic
complexity.
Signed-off-by: Michiel Kalkman <michiel@nosuchtype.com>
> chore: Split params parsing to reduce complexity

- src/errors.rs
- src/model.rs
This PR discloses original `serde_json::Error`.
It's hard to debug large models if errors are suppressed.
> Don't suppress errors of serde_json

- .travis.yml
This removes codecov from the travis plan. This will also require removing the webhook at https://github.com/michiel/jsonapi-rust/settings/hooks
> ci: Remove codecov from travis-ci build steps

- data/resource_004.json
- src/api.rs
- src/model.rs
- tests/api_test.rs
A valid JSON API response may not include a `data` attribute in the relationships. I've added an additional `data/resource_004.json` and test case.
This may help me in resolving some of the problems I am experiencing with #35.
> make Relationship data an Option<IdentifierData>

- .gitignore
- README.md
- src/api.rs
- src/array.rs
- src/lib.rs
- src/model.rs
Primary objective of this commit is to create some top-level documentation
in `src/lib.rs` to provide a variety of examples of how to use the
content of this crate.
This commit also includes some documentation for each of the modules to
provide a more clear explanation of the contents of those modules and
how to use them.
> doc: Update documentation throughout repository with examples

- src/api.rs
- src/lib.rs
- src/model.rs
- tests/api_test.rs
Adds a test to demonstrate `PartialEq` when comparing two parsed
`JsonApiDocument` objects. Useful to demonstrate that ordering of
attributes / keys within the JSON:API document are irrelevant when
comparing two similar documents.
Adds additional docs to various functions for better understanding of
this crate's implementation
> test: Add test to demonstrate `PartialEq`

- data/author_tolkien.json
- src/model.rs
- tests/model_test.rs
This PR builds on the issue identified in #37 and proposes a solution to eliminate the stack overflow issue discovered by the tests. This forks the branch used in that PR and makes modifications to fix the problem.
The test added in #37 for `tests/models_test.rs` demonstrates the stack overflow. All tests in this PR should now pass successfully. 
It should be noted that my changes here modify the assertions from the original forked code. Although capable of creating the overflow bug they do not check for document equivalence.
The changes here expose a way for the code to prevent getting stuck in an infinitely recursive loop by tracking nodes / resource object relationships that have already been visited as part of the recursive call. When the recursive calls visit a node that they've …
> bug: stack overflow error with JsonApiModel::resource_to_attrs

- src/api.rs
- src/lib.rs
- src/model.rs
- tests/api_test.rs
- tests/model_test.rs
This largely addresses the comments in #24 - it converts the top-level `JsonApiDocument` from a `struct` into an `enum` which then uses two new `struct` types (`DocumentError` and `DocumentData`) to handle JSON:API specification validation.
This change allows us to leverage Rust's type system to handle some of the primitive validations and assertions against the v1.0 specification instead of having to write validators to check for illegal combinations of `error` and `data`. Although this doesn't completely address those conditions - it does at least address the main separation between an "error" document and one which contains data.
Note that this is a breaking change to backwards API compatibility - largely because `JsonApiDocument` is now an `enum`.
This PR also includes a few …
> Improve document validation with more intuitive enum and struct use

- Cargo.toml
This resolves security advisories for the regex and thread_local crates, for which queryst 2.x relied on vulnerable versions.
regex: https://github.com/advisories/GHSA-m5pq-gvj9-9vr8
thread_local: https://github.com/advisories/GHSA-9hpw-r23r-xgm5
> build(deps): Update queryst to 3.x
